version: "3.3"
services:

  express:
    build:
      context: ./express-server
      dockerfile: Dockerfile.test
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - mysql
      - elasticsearch
    ports:
      - "3000:3000"
    networks:
      - nosqlnet
      - sqlnet

  mysql:
    image: mysql/mysql-server:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities-test
      - MYSQL_USER=development
      - MYSQL_PASSWORD=development
    volumes:
      - ./sql-test-setup:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - sqlnet

  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - nosqlnet
      volumes:
        - ./elastic-test-data:/usr/share/elasticsearch/data
      environment:
        - node.name=elasticsearch
        - cluster.name=es-docker-cluster
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "http.cors.allow-origin=http://localhost"
        - "http.cors.enabled=true"
        - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
        - "http.cors.allow-credentials=true"
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        - xpack.security.enabled=false
      ulimits:
        memlock:
          soft: -1
          hard: -1
        nofile:
          soft: 65536
          hard: 65536
        nproc: 65535

  kibana:
      image: docker.elastic.co/kibana/kibana:8.0.0
      environment:
        - ELASTICSEARCH_URL=http://192.168.176.2:9200
        - xpack.security.enabled=false
        - xpack.monitoring.enabled=false
        - xpack.ml.enabled=false
        - xpack.graph.enabled=false
        - xpack.reporting.enabled=false
        - xpack.grokdebugger.enabled=false
      ports:
        - "5601:5601"
      networks:
        - nosqlnet
      depends_on:
        - elasticsearch


networks:

  nosqlnet:
    driver: bridge
  sqlnet:
    driver: bridge
