version: "3.3"
services:

  express:
    build:
      context: ./express-server
      dockerfile: Dockerfile.test
    depends_on:
      - mysql
      - elasticsearch
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "30:3000"

  elasticsearch:
      build: elasticsearch/
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - "92:9200"
        - "93:9300"
      environment:
        - MAX_OPEN_FILES=1048576
      cap_add:
        - IPC_LOCK
      ulimits:
        memlock:
          soft: -1
          hard: -1

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities-test
      - MYSQL_USER=development
      - MYSQL_PASSWORD=development
    ports:
      - "33:3306"

  migrations:
    image: micheleminno/db-migrations:latest
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
