version: "3.3"

services:

  angular:
    image: micheleminno/angular-client:latest
    build: ./angular-client
    ports:
      - "4200:4200"

  express:
    image: micheleminno/express-server:latest
    build: ./express-server
    depends_on:
      - mysql
      - elasticsearch
    ports:
      - "3000:3000"
    networks:
      - sqlnet
      - nosqlnet

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
     - nosqlnet
    environment:
      - MAX_OPEN_FILES=1048576
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - nosqlnet
    depends_on:
      - elasticsearch

  mysql:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities
      - MYSQL_USER=production
      - MYSQL_PASSWORD=production
    ports:
      - "3306:3306"
    volumes:
      - ./sql-setup:/docker-entrypoint-initdb.d
    networks:
      - sqlnet

networks:

  nosqlnet:
    driver: bridge
  sqlnet:
    driver: bridge
