version: "3.3"
services:
  angular:
    image: micheleminno/real-affinities:latest
    build:
      context: ./angular-client
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "4200:4200"

  express:
    image: micheleminno/real-affinities:latest
    build:
      context: ./express-server
    depends_on:
      - mysql
      - elasticsearch
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  elasticsearch:
    image: micheleminno/elasticsearch:latest
    working_dir: /data
    command: /elasticsearch/bin/elasticsearch -Epath.conf=/elasticsearch/config
    volumes:
      - /Users/micheleminno/Developer/docker/real-affinities/elasticsearch/data:/data
      - ./elasticsearch/config:/data/config
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - MAX_OPEN_FILES=1048576
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:5.5.2
  #   volumes:
  #     - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
  #   ports:
  #     - "5601:5601"

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities
      - MYSQL_USER=production
      - MYSQL_PASSWORD=production
    ports:
      - "3306:3306"

  migrations:
    image: micheleminno/db-migrations:latest
    environment:
      - NODE_ENV=production
    depends_on:
      - mysql


# to run app
# docker-compose -f docker-compose.yml -p ci up --build
