version: "3.3"
services:

  express:
    build:
      context: ./express-server
      dockerfile: Dockerfile.test
    depends_on:
      - mysql
      - elasticsearch
    ports:
      - "3000:3000"
    networks:
      - nosql
      - sql

  elasticsearch:
      build: ./elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"
      networks:
        - nosql
      environment:
        - MAX_OPEN_FILES=1048576
      cap_add:
        - IPC_LOCK
      ulimits:
        memlock:
          soft: -1
          hard: -1

  kibana:
      build: kibana/
      volumes:
        - ./kibana/config/:/usr/share/kibana/config
      ports:
        - "5601:5601"
      networks:
        - nosql
      depends_on:
        - elasticsearch

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities-test
      - MYSQL_USER=development
      - MYSQL_PASSWORD=development
    ports:
      - "3306:3306"
    networks:
      - sql

  migrations:
    image: micheleminno/db-migrations:latest
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
    networks:
      - sql

networks:

  nosql:
    driver: bridge
  sql:
    driver: bridge
