version: "3.3"

services:

  angular:
    image: micheleminno/angular-client:latest
    build: ./angular-client
    ports:
      - "4200:4200"

  express:
    image: micheleminno/express-server:latest
    build: ./express-server
    ports:
      - "3000:3000"
    networks:
      - sqlnet
      - nosqlnet
    depends_on:
      - mysql
      - elasticsearch

  mysql:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities
      - MYSQL_USER=production
      - MYSQL_PASSWORD=production
    ports:
      - "3306:3306"
    volumes:
      - ./sql-setup:/docker-entrypoint-initdb.d
    networks:
      - sqlnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PASSWORD=password
    restart: always
    ports:
      - 8081:80
    networks:
      - sqlnet
    depends_on:
      - mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - discovery.zen.minimum_master_nodes=1
      - bootstrap.memory_lock=true
      - bootstrap.system_call_filter=false
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
      - "http.cors.allow-origin=http://localhost"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
      - "ES_JAVA_OPTS=-Xms1g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - nosqlnet

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    environment:
      - ELASTICSEARCH_URL=http://192.168.176.2:9200
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.reporting.enabled=false
      - xpack.grokdebugger.enabled=false
    ports:
      - "5601:5601"
    networks:
      - nosqlnet
    depends_on:
      - elasticsearch


networks:

  nosqlnet:
    driver: bridge
  sqlnet:
    driver: bridge
