version: "3.3"
services:
  angular-client:
    build:
      context: ./angular-client
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "42:4200"

  express:
    build:
      context: ./express-server
    depends_on:
      - mysql
      - elasticsearch
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "30:3000"

  elasticsearch:
    image: micheleminno/elasticsearch:latest
    working_dir: /data
    command: /elasticsearch/bin/elasticsearch -Epath.conf=/elasticsearch/config
    volumes:
      - /Users/micheleminno/Developer/docker/real-affinities/elasticsearch/data:/data
      - ./elasticsearch/config:/data/config
    ports:
      - "92:9200"
      - "93:9300"
    environment:
      - MAX_OPEN_FILES=1048576
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=real-affinities-test
      - MYSQL_USER=development
      - MYSQL_PASSWORD=development
    ports:
      - "33:3306"

  migrations:
    image: micheleminno/db-migrations:latest
    environment:
      - NODE_ENV=development
    depends_on:
      - mysql
