
FROM ubuntu:16.04

USER root

RUN apt-get update
RUN apt-get -qq update
RUN apt-get install -y build-essential
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash
RUN apt-get install -y nodejs

EXPOSE 3000

ENV NODE_ENV development

RUN mkdir /app

WORKDIR /app

ADD package.json .

RUN apt-get install make gcc g++ python

RUN npm install -gq mocha

RUN npm install -q

ADD . .

CMD mocha "test/**/*.js" --timeout 20000
