
FROM node:fermium-buster

USER root

RUN apt-get update

EXPOSE 3000

ENV NODE_ENV development

RUN mkdir /app

WORKDIR /app

ADD package.json .

RUN apt-get install make gcc g++ python

RUN npm install -gq mocha

RUN npm install -q

ADD . .

CMD mocha "test/**/*.js" --timeout 20000
