
FROM node:fermium-buster

USER root

RUN apt-get update

ENV NODE_ENV development

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json .

RUN apt-get install make gcc g++ python bash

RUN npm install -gq mocha

RUN npm install -q

COPY . .

EXPOSE 3000

CMD ["npm", "test"]

#CMD wait-for-it.sh -t 30 localhost:9200 -- mocha "./test/**/*.js" --timeout 40000
