#Step 1
FROM node:8.1.4-alpine

#Step 2
RUN mkdir -p /usr/src/app

#Step 3
WORKDIR /usr/src/app

#Step 4
COPY package.json /usr/src/app

#Step 5
RUN apk add --no-cache make gcc g++ python bash

#Step 6
RUN npm install -gq mocha

#Step 7
RUN npm install -q

#Step 8
COPY . /usr/src/app

#Step 9
EXPOSE 3000

#Step 10
ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/e1f115e4ca285c3c24e847c4dd4be955e0ed51c2/wait-for-it.sh /usr/src/app/wait-for-it.sh

#Step 11
RUN chmod 777 /usr/src/app/wait-for-it.sh

#Step 12
CMD /usr/src/app/wait-for-it.sh -t 30 0.0.0.0:92 -- mocha "./test/**/*.js" --timeout 40000
